[general]
live_config_reload = false
ipc_socket = false

[window]
startup_mode = "Fullscreen"
dynamic_padding = true
title = "ASCII-MC"
dynamic_title = false
class = { instance = "ascii-mc", general = "ascii-mc" }

[font]
normal = { family = "Terminus", style = "Regular" }
bold = { family = "Terminus", style = "Bold" }
size = 11.5

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.cursor]
text = "#000000"
cursor = "#ffffff"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#ffffff"

[colors.normal]
black = "#000000"
red = "#aa0000"
green = "#00aa00"
yellow = "#aa5500"
blue = "#0000aa"
magenta = "#aa00aa"
cyan = "#00aaaa"
white = "#aaaaaa"

[colors.bright]
black = "#555555"
red = "#ff5555"
green = "#55ff55"
yellow = "#ffff55"
blue = "#5555ff"
magenta = "#ff55ff"
cyan = "#55ffff"
white = "#ffffff"

[scrolling]
history = 0

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { mods = "Control", key = "à", action = "ResetFontSize" },
]

[debug]
log_level = "Off"
